name: Clean Workflows

on:
  workflow_dispatch:

  schedule:
    - cron: '15 9 */7 * *'
jobs:
  delete_runs:
    runs-on: ubuntu-latest
    steps:
    - name: Delete workflow runs
      uses: dmvict/clean-workflow-runs@v1.0.0
      with:
       token: ${{ secrets.REPO_TOKEN }}
       repo: ixmu/smartdns-conf
       workflow_id: Update.yml,clean.yml
       branch: main
       run_conclusions: |
          failure
          timed_out
       save_period: 30
       save_min_runs_number: 1
       dry: true
